/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: test.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "test.pb-c.h"
void   yuza__person__phone_number__comment__init
                     (YUZA__Person__PhoneNumber__Comment         *message)
{
  static const YUZA__Person__PhoneNumber__Comment init_value = YUZA__PERSON__PHONE_NUMBER__COMMENT__INIT;
  *message = init_value;
}
void   yuza__person__phone_number__init
                     (YUZA__Person__PhoneNumber         *message)
{
  static const YUZA__Person__PhoneNumber init_value = YUZA__PERSON__PHONE_NUMBER__INIT;
  *message = init_value;
}
void   yuza__person__init
                     (YUZA__Person         *message)
{
  static const YUZA__Person init_value = YUZA__PERSON__INIT;
  *message = init_value;
}
size_t yuza__person__get_packed_size
                     (const YUZA__Person *message)
{
  assert(message->base.descriptor == &yuza__person__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t yuza__person__pack
                     (const YUZA__Person *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &yuza__person__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t yuza__person__pack_to_buffer
                     (const YUZA__Person *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &yuza__person__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
YUZA__Person *
       yuza__person__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (YUZA__Person *)
     protobuf_c_message_unpack (&yuza__person__descriptor,
                                allocator, len, data);
}
void   yuza__person__free_unpacked
                     (YUZA__Person *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &yuza__person__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor yuza__person__phone_number__comment__field_descriptors[1] =
{
  {
    "comment",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(YUZA__Person__PhoneNumber__Comment, comment),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned yuza__person__phone_number__comment__field_indices_by_name[] = {
  0,   /* field[0] = comment */
};
static const ProtobufCIntRange yuza__person__phone_number__comment__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor yuza__person__phone_number__comment__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "YUZA.Person.PhoneNumber.Comment",
  "Comment",
  "YUZA__Person__PhoneNumber__Comment",
  "YUZA",
  sizeof(YUZA__Person__PhoneNumber__Comment),
  1,
  yuza__person__phone_number__comment__field_descriptors,
  yuza__person__phone_number__comment__field_indices_by_name,
  1,  yuza__person__phone_number__comment__number_ranges,
  (ProtobufCMessageInit) yuza__person__phone_number__comment__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const YUZA__Person__PhoneType yuza__person__phone_number__type__default_value = YUZA__PERSON__PHONE_TYPE__HOME;
static const ProtobufCFieldDescriptor yuza__person__phone_number__field_descriptors[3] =
{
  {
    "number",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(YUZA__Person__PhoneNumber, number),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(YUZA__Person__PhoneNumber, has_type),
    offsetof(YUZA__Person__PhoneNumber, type),
    &yuza__person__phone_type__descriptor,
    &yuza__person__phone_number__type__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "comment",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(YUZA__Person__PhoneNumber, comment),
    &yuza__person__phone_number__comment__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned yuza__person__phone_number__field_indices_by_name[] = {
  2,   /* field[2] = comment */
  0,   /* field[0] = number */
  1,   /* field[1] = type */
};
static const ProtobufCIntRange yuza__person__phone_number__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor yuza__person__phone_number__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "YUZA.Person.PhoneNumber",
  "PhoneNumber",
  "YUZA__Person__PhoneNumber",
  "YUZA",
  sizeof(YUZA__Person__PhoneNumber),
  3,
  yuza__person__phone_number__field_descriptors,
  yuza__person__phone_number__field_indices_by_name,
  1,  yuza__person__phone_number__number_ranges,
  (ProtobufCMessageInit) yuza__person__phone_number__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue yuza__person__phone_type__enum_values_by_number[3] =
{
  { "MOBILE", "YUZA__PERSON__PHONE_TYPE__MOBILE", 0 },
  { "HOME", "YUZA__PERSON__PHONE_TYPE__HOME", 1 },
  { "WORK", "YUZA__PERSON__PHONE_TYPE__WORK", 2 },
};
static const ProtobufCIntRange yuza__person__phone_type__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex yuza__person__phone_type__enum_values_by_name[3] =
{
  { "HOME", 1 },
  { "MOBILE", 0 },
  { "WORK", 2 },
};
const ProtobufCEnumDescriptor yuza__person__phone_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "YUZA.Person.PhoneType",
  "PhoneType",
  "YUZA__Person__PhoneType",
  "YUZA",
  3,
  yuza__person__phone_type__enum_values_by_number,
  3,
  yuza__person__phone_type__enum_values_by_name,
  1,
  yuza__person__phone_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor yuza__person__field_descriptors[4] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(YUZA__Person, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "id",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(YUZA__Person, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "email",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(YUZA__Person, email),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "phone",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(YUZA__Person, n_phone),
    offsetof(YUZA__Person, phone),
    &yuza__person__phone_number__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned yuza__person__field_indices_by_name[] = {
  2,   /* field[2] = email */
  1,   /* field[1] = id */
  0,   /* field[0] = name */
  3,   /* field[3] = phone */
};
static const ProtobufCIntRange yuza__person__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor yuza__person__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "YUZA.Person",
  "Person",
  "YUZA__Person",
  "YUZA",
  sizeof(YUZA__Person),
  4,
  yuza__person__field_descriptors,
  yuza__person__field_indices_by_name,
  1,  yuza__person__number_ranges,
  (ProtobufCMessageInit) yuza__person__init,
  NULL,NULL,NULL    /* reserved[123] */
};
