/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: test.proto */

#ifndef PROTOBUF_C_test_2eproto__INCLUDED
#define PROTOBUF_C_test_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _YUZA__Person YUZA__Person;
typedef struct _YUZA__Person__PhoneNumber YUZA__Person__PhoneNumber;
typedef struct _YUZA__Person__PhoneNumber__Comment YUZA__Person__PhoneNumber__Comment;


/* --- enums --- */

typedef enum _YUZA__Person__PhoneType {
  YUZA__PERSON__PHONE_TYPE__MOBILE = 0,
  YUZA__PERSON__PHONE_TYPE__HOME = 1,
  YUZA__PERSON__PHONE_TYPE__WORK = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(YUZA__PERSON__PHONE_TYPE)
} YUZA__Person__PhoneType;

/* --- messages --- */

struct  _YUZA__Person__PhoneNumber__Comment
{
  ProtobufCMessage base;
  char *comment;
};
#define YUZA__PERSON__PHONE_NUMBER__COMMENT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&yuza__person__phone_number__comment__descriptor) \
    , NULL }


struct  _YUZA__Person__PhoneNumber
{
  ProtobufCMessage base;
  char *number;
  protobuf_c_boolean has_type;
  YUZA__Person__PhoneType type;
  YUZA__Person__PhoneNumber__Comment *comment;
};
#define YUZA__PERSON__PHONE_NUMBER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&yuza__person__phone_number__descriptor) \
    , NULL, 0, YUZA__PERSON__PHONE_TYPE__HOME, NULL }


struct  _YUZA__Person
{
  ProtobufCMessage base;
  char *name;
  int32_t id;
  char *email;
  size_t n_phone;
  YUZA__Person__PhoneNumber **phone;
};
#define YUZA__PERSON__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&yuza__person__descriptor) \
    , NULL, 0, NULL, 0,NULL }


/* YUZA__Person__PhoneNumber__Comment methods */
void   yuza__person__phone_number__comment__init
                     (YUZA__Person__PhoneNumber__Comment         *message);
/* YUZA__Person__PhoneNumber methods */
void   yuza__person__phone_number__init
                     (YUZA__Person__PhoneNumber         *message);
/* YUZA__Person methods */
void   yuza__person__init
                     (YUZA__Person         *message);
size_t yuza__person__get_packed_size
                     (const YUZA__Person   *message);
size_t yuza__person__pack
                     (const YUZA__Person   *message,
                      uint8_t             *out);
size_t yuza__person__pack_to_buffer
                     (const YUZA__Person   *message,
                      ProtobufCBuffer     *buffer);
YUZA__Person *
       yuza__person__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   yuza__person__free_unpacked
                     (YUZA__Person *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*YUZA__Person__PhoneNumber__Comment_Closure)
                 (const YUZA__Person__PhoneNumber__Comment *message,
                  void *closure_data);
typedef void (*YUZA__Person__PhoneNumber_Closure)
                 (const YUZA__Person__PhoneNumber *message,
                  void *closure_data);
typedef void (*YUZA__Person_Closure)
                 (const YUZA__Person *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor yuza__person__descriptor;
extern const ProtobufCMessageDescriptor yuza__person__phone_number__descriptor;
extern const ProtobufCMessageDescriptor yuza__person__phone_number__comment__descriptor;
extern const ProtobufCEnumDescriptor    yuza__person__phone_type__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_test_2eproto__INCLUDED */
